/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaModelo.M_Producto;
import CapaControlador.Conexion;
import CapaControlador.N_Servicio;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edgard
 */
public class FrmServicio extends javax.swing.JInternalFrame {

    private Conexion SQL = new Conexion();
    private Connection cn = SQL.conectar();
    int contador = 0;
    private String accion = "guardar";

    /**
     * Creates new form FrmProducto
     */
    public FrmServicio() {
        initComponents();
        mostrar("");
        inhabilitar();
        cargar_categoria();
        txtidcategoria.setVisible(false);
        ocultar_columnas();
    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            N_Servicio func = new N_Servicio();
            modelo = func.mostrar(buscar);
            tablalistado.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    private void cargar_categoria() {
        String sql = "sp_listar_categoria";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cbocategoria.addItem(rs.getString("descripcion"));

            }
            contador++;
        } catch (Exception ex) {
            Logger.getLogger(FrmServicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void inhabilitar() {
        txtidproducto.setEnabled(false);
        txtserie.setEnabled(false);
        txtproducto.setEnabled(false);
        txtpreciocompra.setEnabled(false);
        txtprecioventa.setEnabled(false);
        dcfecha_ingreso.setEnabled(false);
        dcfecha_vencimiento.setEnabled(false);
        cbocategoria.setEnabled(false);
        txtidcategoria.setEnabled(false);
        txtbuscar.setEnabled(false);

        btnbuscar.setEnabled(false);
        btnguardar.setEnabled(false);
        btnsalir.setEnabled(false);

        btnnuevo.setEnabled(true);
        btnsalir.setEnabled(true);
    }

    public void habilitar() {
        txtidproducto.setEnabled(true);
        txtserie.setEnabled(true);
        txtproducto.setEnabled(true);
        txtpreciocompra.setEnabled(true);
        txtprecioventa.setEnabled(true);
        dcfecha_ingreso.setEnabled(true);
        dcfecha_vencimiento.setEnabled(true);
        cbocategoria.setEnabled(true);
        txtidcategoria.setEnabled(true);
        txtbuscar.setEnabled(true);

        btnbuscar.setEnabled(true);
        btnguardar.setEnabled(true);
        btnsalir.setEnabled(true);

    }

    public void Limpiar() {
        txtidproducto.setText("");
        txtserie.setText("");
        txtproducto.setText("");
        txtpreciocompra.setText("");
        txtprecioventa.setText("");
        cbocategoria.setSelectedIndex(0);

    }

    void ocultar_columnas() {
        tablalistado.getColumnModel().getColumn(8).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(8).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(8).setPreferredWidth(0);

    }

    void generarId() {
        N_Servicio func = new N_Servicio();
        DecimalFormat formato = new DecimalFormat("0000");
        txtidproducto.setText(formato.format(func.generarIdProducto()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtserie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidproducto = new javax.swing.JTextField();
        txtproducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpreciocompra = new javax.swing.JTextField();
        txtprecioventa = new javax.swing.JTextField();
        txtidcategoria = new javax.swing.JTextField();
        cbocategoria = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dcfecha_ingreso = new com.toedter.calendar.JDateChooser();
        dcfecha_vencimiento = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel2.setText("Serie:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE LA VENTA"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setText("Velocidad");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel2.add(txtidproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 71, -1));
        jPanel2.add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 147, -1));

        jLabel4.setText("Precio Compra:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel5.setText("Precio Venta:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel6.setText("Promocion");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));
        jPanel2.add(txtpreciocompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 73, -1));
        jPanel2.add(txtprecioventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 73, -1));
        jPanel2.add(txtidcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 14, -1));

        cbocategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(cbocategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 116, -1));

        jLabel7.setText("Fecha Ingreso:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jLabel8.setText("Fecha Vencimiento:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));
        jPanel2.add(dcfecha_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 156, -1));
        jPanel2.add(dcfecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 156, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 710, 150));

        jLabel9.setText("BUSCAR POR CODIGO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 250, 30));

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/lupa.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 120, 50));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salir1.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 120, 50));

        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalistadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablalistado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 720, 154));

        btneliminar.setBackground(new java.awt.Color(153, 153, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/eliminar.gif"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, 70));

        btnnuevo.setBackground(new java.awt.Color(153, 153, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/add.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 60));

        btnguardar.setBackground(new java.awt.Color(153, 153, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/guardar.gif"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/tienda.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/etiqueta-de-venta.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbocategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocategoriaActionPerformed
        try {
            Statement st = cn.createStatement();
            if (contador >= 0) {
                String sql = "select * from categoria where descripcion='" + cbocategoria.getSelectedItem() + "'";
                ResultSet rs = st.executeQuery(sql);
                rs.next();
                this.txtidcategoria.setText(String.valueOf(rs.getInt("idcategoria")));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_cbocategoriaActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        accion = "guardar";
        btnguardar.setText("Guardar");
        habilitar();
        Limpiar();
        generarId();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (txtidproducto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ingrese Producto");
            txtproducto.requestFocus();
            return;
        }
        if (txtprecioventa.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ingrese precio venta");
            txtprecioventa.requestFocus();
            return;
        }
        if (txtpreciocompra.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ingrese precio compra");
            txtpreciocompra.requestFocus();
            return;
        }
        
        M_Producto dts = new M_Producto();
        N_Servicio func = new N_Servicio();
        
        dts.setIdproducto(txtidproducto.getText());
        dts.setSerie(txtserie.getText());
        dts.setNombre(txtproducto.getText());
        dts.setP_venta(Double.parseDouble(txtpreciocompra.getText()));
        dts.setP_compra(Double.parseDouble(txtprecioventa.getText()));
        
        Calendar cal;
        int d,m,a;
        
        cal=dcfecha_ingreso.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;
        dts.setF_ingreso(new Date(a,m,d));
        
        
        cal=dcfecha_vencimiento.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;
        dts.setF_vencimiento(new Date(a,m,d));
        
        dts.setIdcategoria(Integer.parseInt(txtidcategoria.getText()));
        
        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Producto registrado");
                mostrar("");
                Limpiar();
                inhabilitar();
                ocultar_columnas();
            }
            
        }else if (accion.equals("editar")) {
             if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Producto editado con exito");
                mostrar("");
                Limpiar();
                inhabilitar();
                ocultar_columnas();
            }
            
        }
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        M_Producto dts = new M_Producto();
        N_Servicio func = new N_Servicio();
        
        if (!txtidproducto.getText().equals("") && !txtserie.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane,"Desea eliminar el servicio","Confirmar",2);
            if (confirmacion == 0) {
                dts.setIdproducto(txtidproducto.getText());
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }   
            
        }else {
            JOptionPane.showConfirmDialog(null, "Debe seleccionar un servicio","Servicio",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void tablalistadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMouseClicked
        btnguardar.setText("Editar");
        habilitar();
        ocultar_columnas();
        btneliminar.setEnabled(true);
        accion="editar";
        int fila = tablalistado.rowAtPoint(evt.getPoint());
        
        txtidproducto.setText(tablalistado.getValueAt(fila, 0).toString());
        txtserie.setText(tablalistado.getValueAt(fila, 1).toString());
        txtproducto.setText(tablalistado.getValueAt(fila,2).toString());
        dcfecha_ingreso.setDate(Date.valueOf(tablalistado.getValueAt(fila,3).toString()));
        dcfecha_vencimiento.setDate(Date.valueOf(tablalistado.getValueAt(fila, 4).toString()));
        txtpreciocompra.setText(tablalistado.getValueAt(fila, 5).toString());
        txtprecioventa.setText(tablalistado.getValueAt(fila, 6).toString());
        txtidcategoria.setText(tablalistado.getValueAt(fila, 8).toString());
        cbocategoria.setSelectedItem(tablalistado.getValueAt(fila, 9).toString());
        
    }//GEN-LAST:event_tablalistadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cbocategoria;
    private com.toedter.calendar.JDateChooser dcfecha_ingreso;
    private com.toedter.calendar.JDateChooser dcfecha_vencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablalistado;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtidcategoria;
    private javax.swing.JTextField txtidproducto;
    private javax.swing.JTextField txtpreciocompra;
    private javax.swing.JTextField txtprecioventa;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtserie;
    // End of variables declaration//GEN-END:variables
}
